if: false # Keep this line for now to ensure the stuck workflow clears

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # This workflow runs when changes are pushed to the 'main' branch

permissions: # NEW: Add this permissions block
  contents: read # Allows the workflow to read your repository's contents
  pages: write   # Allows the workflow to write to GitHub Pages
  id-token: write # Required for actions/deploy-pages to authenticate

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Specifies the runner environment (a virtual computer on GitHub)
    timeout-minutes: 10 # This job will automatically cancel if it runs for more than 10 minutes.

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4 # This step gets your website files from your GitHub repository

      - name: Setup GitHub Pages environment
        uses: actions/configure-pages@v5 # This step prepares the environment for GitHub Pages deployment

      - name: Upload website files as an artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './' # This tells the action to take ALL files from the root of your repository
                      # (where your index.html is) and prepare them for deployment.

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # This step actually publishes your website files to GitHub Pages
